config_snmp_pp.h.in: add missing include
config_snmp_pp.h.in uses struct sockaddr and socklen_t but does not
include sys/socket.h where it is defined. So a user program including
config_snmp_pp.h fails with an error like:

  In file included from /usr/include/libagent.h:206:0,
                   from /usr/include/agent_pp/agent++.h:36,
                   from /.../test.cpp:8:
  /usr/include/snmp_pp/config_snmp_pp.h:147:11: error: 'socklen_t' does not name a type
     typedef socklen_t SocketLengthType;
             ^

Add the include for Linux only, since it might be defined elsewhere on
other platforms.

Signed-off-by: Luca Ceresoli <luca@lucaceresoli.net>